In [2]:
n.sample<-200
x.min<-0
x.max<-6
h<-(x.max-x.min)/n.sample
μ<-seq(from=x.min, by=h, length.out=n.sample+1)

data<-c(4,1,3,1,3)
dataSum<-sum(data)

lambda<-5
uniform.alpha<-dataSum+1
jeffrey.alpha<-dataSum+0.5




uniform.posterior<-dgamma(μ, shape=uniform.alpha, rate=lambda)
jeffrey.posterior<-dgamma(μ, shape=jeffrey.alpha, rate=lambda)

Median<-function(posterior){
    for(i in 1:length(μ)){
        S<-h*sum(head(posterior, -i))
        cat("\n", S)
        if(floor(S*100)==50){
            med<-length(μ)-i
            return(med)
            break
        }
    }
}

Median2<-function(posterior){
    for(i in 1:length(μ)){
        S<-h*sum(head(posterior, i))
        cat("\n", S)
        if(floor(S*100)==50){
            return(i)
            break
        }
    }
}

Median(uniform.posterior)
Median2(uniform.posterior)


 0.9998244
 0.9998074
 0.9997887
 0.9997684
 0.9997461
 0.9997218
 0.9996952
 0.9996662
 0.9996345
 0.9995999
 0.9995622
 0.9995211
 0.9994762
 0.9994274
 0.9993741
 0.9993162
 0.999253
 0.9991844
 0.9991096
 0.9990284
 0.99894
 0.998844
 0.9987397
 0.9986265
 0.9985036
 0.9983702
 0.9982255
 0.9980687
 0.9978987
 0.9977146
 0.9975152
 0.9972993
 0.9970658
 0.9968132
 0.9965402
 0.9962452
 0.9959265
 0.9955825
 0.9952112
 0.9948108
 0.994379
 0.9939138
 0.9934126
 0.9928731
 0.9922926
 0.9916681
 0.9909969
 0.9902756
 0.989501
 0.9886697
 0.9877777
 0.9868214
 0.9857966
 0.9846989
 0.983524
 0.9822669
 0.9809228
 0.9794864
 0.9779524
 0.976315
 0.9745683
 0.9727063
 0.9707225
 0.9686102
 0.9663627
 0.9639727
 0.961433
 0.9587359
 0.9558737
 0.9528383
 0.9496214
 0.9462148
 0.9426097
 0.9387974
 0.934769
 0.9305155
 0.9260277
 0.9212965
 0.9163125
 0.9110665
 0.9055492
 0.8997515
 0.8936642
 0.8872785
 0.8805855
 0.8735767
 0.8662439
 0.8585791
 0.8505749
 0.8422242
 0.8335205
 0.82445

[1] 85


 0
 3.497077e-20
 1.23323e-16
 1.389136e-14
 3.879956e-13
 5.073632e-12
 4.103195e-11
 2.378281e-10
 1.078789e-09
 4.053618e-09
 1.311945e-08
 3.760871e-08
 9.749044e-08
 2.32168e-07
 5.142449e-07
 1.06987e-06
 2.107357e-06
 3.955712e-06
 7.114528e-06
 1.231632e-05
 2.060196e-05
 3.340914e-05
 5.267328e-05
 8.093949e-05
 0.0001214833
 0.0001784374
 0.0002569214
 0.0003631697
 0.0005046542
 0.0006901971
 0.000930069
 0.001236068
 0.001621578
 0.002101598
 0.002692744
 0.00341322
 0.00428276
 0.005322526
 0.006554989
 0.008003768
 0.00969344
 0.01164933
 0.01389728
 0.01646336
 0.01937366
 0.02265395
 0.02632941
 0.03042435
 0.03496193
 0.03996386
 0.04545018
 0.05143896
 0.05794614
 0.06498526
 0.07256736
 0.08070076
 0.08939101
 0.09864075
 0.1084497
 0.1188147
 0.1297294
 0.1411849
 0.1531692
 0.1656675
 0.1786627
 0.1921349
 0.206062
 0.2204198
 0.235182
 0.2503208
 0.2658066
 0.2816087
 0.2976951
 0.3140331
 0.3305893
 0.3473299
 0.3642209
 0.3812283
 0.3983182
 0.4154572
 0.432612

[1] 85

In [4]:
CI.upper<-function(posterior){
    for(i in 1:length(μ)){
        S<-h*sum(head(tail(uniform.posterior, -(CI.lower(uniform.posterior)-1)), -i))
        if(ceiling(S*100)==95){
            index<-length(μ)-i
            return(index)
            break
        }
    }
}
CI.lower<-function(posterior){
    for(i in 1:length(μ)){
        if(posterior[i]>0.12){
            return(i)
            break
        }
    }
}


uniform.posterior<-dgamma(μ, shape=uniform.alpha, rate=lambda)
jeffrey.posterior<-dgamma(μ, shape=jeffrey.alpha, rate=lambda)


Out<-function(posterior){
    cat("Lower bound\nIndex:", CI.lower(posterior),
    "\nμ:", μ[CI.lower(posterior)],
    "\nPosterior:", posterior[CI.lower(posterior)])
    cat("\n\n\n\n")

    cat("Upper bound\nIndex:", CI.upper(posterior),
    "\nμ:", μ[CI.upper(posterior)],
    "\nPosterior:", posterior[CI.upper(posterior)])
    cat("\n\n\n\n")

    cat("95% Confidence Interval:", h*sum(tail(head(posterior, CI.upper(posterior)), -(CI.lower(posterior)-1))))
    cat("\n\n\n")

    #tail(head(posterior, CI.upper(posterior)), -(CI.lower(posterior)-1))
}
Out(jeffrey.posterior)


cat("\n\n")
qgamma(0.025, shape=jeffrey.alpha, rate=lambda)
qgamma(0.975, shape=jeffrey.alpha, rate=lambda)

Lower bound
Index: 45 
µ: 1.32 
Posterior: 0.1321776



Upper bound
Index: 138 
µ: 4.11 
Posterior: 0.05436641



95% Confidence Interval: 0.9542994






[1] 1.311972

[1] 4.064647

In [9]:
x<-1:3
y<-2:5
z<-c(1,0,1)

gianni1<-function(a,b){a*b}
gianni2<-function(a,b){sum((a*b)+z)}


grid1<- outer(x, y, Vectorize(gianni1))
grid1
grid2<- outer(x, y, Vectorize(gianni2))
grid2



[,1] [,2] [,3] [,4]
[1,] 2    3     4    5  
[2,] 4    6     8   10  
[3,] 6    9    12   15

[,1] [,2] [,3] [,4]
[1,]  8   11   14   17  
[2,] 14   20   26   32  
[3,] 20   29   38   47

In [1]:
x<-1:3
y<-2:5
z<-rep(1,3)

gianni1<-function(a,b){a*b}


grid1<- outer(x, y, Vectorize(gianni1))
grid1
grid1[1,]

for(i in 1:length(x)){
    S<-sum( grid1[i,] )
    cat("\n",S)
}

[,1] [,2] [,3] [,4]
[1,] 2    3     4    5  
[2,] 4    6     8   10  
[3,] 6    9    12   15

[1] 2 3 4 5


 14
 28
 42

In [ ]:
persp(alphas, betas, joint.post, xlab="α", ylab="β", zlab="P(α,β | Xk,M)", col="white", ticktype ='detailed',
      xlim=c(x_min,x_max), ylim=c(0,y_max), theta=80, phi=30, d=1, shade=0.5)

In [11]:
x<-1:3
y<-2:5
z<-rep(1,3)

giannino<-function(a,b){a*b}


giannino(x, y)

Vectorize(giannino, "a")(x, y)

Warning message in a * b:
"longer object length is not a multiple of shorter object length"

[1]  2  6 12  5

[,1] [,2] [,3]
[1,] 2     4    6  
[2,] 3     6    9  
[3,] 4     8   12  
[4,] 5    10   15

In [6]:
x<-1:3
y<-2:5
z<-rep(1,3)
y.true<-2

gianni1<-function(a,b){a*b}


grid1<- outer(x, y.true, Vectorize(gianni1))
grid1

[,1]
[1,] 2   
[2,] 4   
[3,] 6

In [ ]:
# Exercise 2

library(tidyverse)

alpha<-readline("Enter alpha unkonwn true value: ") %>% as.numeric()              
beta<-readline("Enter beta unkonwn true value (beta>0): ") %>% as.numeric()
N<-readline("Enter data set dimension: ") %>% as.numeric()

set.seed(347689)                #Create a dateset
theta_k<-runif(N,-pi/2,pi/2)
x_k<-beta*tan(theta_k)+alpha


x_min<-alpha-10
x_max<-alpha+10
y_max<-beta+10
delta.x<-(x_max-x_min)/(1000)
delta.y<-y_max/(y_max*10)
alphas<-seq(from=x_min, to=x_max, by=delta.x)
betas<-seq(from=0, to=y_max, by=delta.y)



log.joint.posterior <- function(a,b){
  sum( log( b/(b^2+(x_k-a)^2) )) 
}

log.joint.star<-outer(alphas, betas, Vectorize(log.joint.posterior))
joint.post.star<-exp(log.joint.star)
joint.post<-joint.post.star/(delta.x*delta.y*sum(joint.post.star))
delta.x*delta.y*sum(joint.post)

alpha.post<-NULL
for(i in 1:length(alphas)){
    S<-delta.y*sum( joint.post[i,] )
    alpha.post<-c(alpha.post, S)
}
beta.post<-NULL
for(i in 1:length(betas)){
    S<-delta.x*sum( joint.post[,i] )
    beta.post<-c(beta.post, S)
}



max.alpha<-alphas[which.max(alpha.post)]
max.beta<-betas[which.max(beta.post)]
cat("Data set mean: ", mean(x_k))
cat("\nAlpha most probable value: ", max.alpha)
cat("\nBeta most probable value: ",  max.beta)

plot(alphas, alpha.post, type="l", col="red", lwd=2, lty=3, xlab="α", ylab="P(α | Xk,M)", main="Alphas posterior distribution")
abline(v=max.alpha, lty=2)
plot(betas, beta.post, type="l", col="blue", lwd=2, lty=3, xlab="β", ylab="P(β | Xk,M)",  main="Betas posterior distribution")
abline(v=max.beta, lty=2)

image(alphas, betas, joint.post, xlab="α", ylab="β")

In [ ]:
#Professor code



# - Generative model
signal <- function(x, a, b, x0, w, t) {
t * (a*exp(-(x-x0)^2/(2*w^2)) + b)
}

# Define model parameters
x0 <- 0 # Signal peak
w <-1 # Signal width
A.true <- 2 # Signal amplitude
B.true <- 1 # Background amplitude
Delta.t <- 5 # Exposure time


# - Generate the observed data
set.seed(205)
xdat <- seq(from=-7*w, to=7*w, by=0.5*w)
s.true <- signal(xdat , A.true , B.true , x0, w, Delta.t)

ddat <- rpois(length(s.true), s.true)
xplot <- seq(from=min(xdat), to=max(xdat), by=0.05*w)
splot <- signal(xplot , A.true , B.true , x0, w, Delta.t)

plot(xplot , splot , xlab="x", ylab="Signal+Background counts")
par(new=TRUE)
xdat.off <- xdat-0.25
plot(xdat.off, ddat , type="s", col="firebrick3", lwd=2,xlim=range(xplot), ylim=range(c(splot , ddat)))



# - Sampling grid for computing posterior
alim <- c(0.0, 4.0)
blim <- c(0.5, 1.5)
Nsamp <- 100
uniGrid <- seq(from=1/(2*Nsamp), to=1-1/(2*Nsamp), by=1/Nsamp)
delta_a <- diff(alim)/Nsamp
delta_b <- diff(blim)/Nsamp
a <- alim[1] + diff(alim)*uniGrid
b <- blim[1] + diff(blim)*uniGrid



# Log posterior
log.post <- function(d, x, a, b, x0, w, t) {
    if(a<0 || b <0) {return(-Inf)} # the effect of the prior
    sum(dpois(d, lambda=signal(x, a, b, x0, w, t), log=TRUE))
}

# Compute log unnormalized posterior , z = ln Pˆ*(a,b|D), on a regular grid
z <- matrix(data=NA, nrow=length(a), ncol=length(b))
for(j in 1:length(a)) {
    for(k in 1:length(b)) {
        z[j,k] <- log.post(ddat , xdat , a[j], b[k], x0, w, Delta.t)
    }
}
z <- z - max(z) # set maximum to zero

# Plot unnormalized 2D posterior as contours.
contour(a, b, exp(z), nlevels = 5, labcex = 0.5, lwd = 2, xlab="amplitude , A", ylab="background , B") 
abline(v=2,h=1,col="grey")



# Compute normalized marginalized posteriors , P(a|D) and P(b|D)
# by summing over other parameter. Normalize by gridding.
p_a_D <- apply(exp(z), 1, sum)
p_a_D <- p_a_D/(delta_a*sum(p_a_D))
p_b_D <- apply(exp(z), 2, sum)
p_b_D <- p_b_D/(delta_b*sum(p_b_D))

# Compute normalized conditional posteriors , P(a|b,D) and P(b|a,D)
# using true values of conditioned parameters. Vectorize(func , par)
# makes a vectorized function out of func in the parameter par.
p_a_bD <- exp(Vectorize(log.post , "a")(ddat , xdat , a, B.true , x0, w, Delta.t))
p_a_bD <- p_a_bD/(delta_a*sum(p_a_bD))
p_b_aD <- exp(Vectorize(log.post , "b")(ddat , xdat , A.true , b, x0, w, Delta.t))
p_b_aD <- p_b_aD/(delta_b*sum(p_b_aD))



par(mfrow=c(2,2), mgp=c(2,0.8,0), mar=c(3.5,3.5,1,1), oma=0.1*c(1,1,1,1))

# Plot the 1D marginalized posteriors
plot(b, p_b_D, xlab="background , B", yaxs="i",
ylim=1.05*c(0,max(p_b_D, p_b_aD)), ylab="P(B | D)  and  P(B | A,D)", type="l", lwd=2)
lines(b, p_b_aD, lwd=2, lty=2)
abline(v=B.true , col="grey")
plot(a, p_a_D, xlab="amplitude , A", yaxs="i", ylim=1.05*c(0,max(p_a_D, p_a_bD)), ylab="P(A | D)  and  P(A | B,D)",
type="l", lwd=2)
lines(a, p_a_bD, lwd=2, lty=2)
abline(v=A.true , col="grey")



# Compute mean , standard deviation , covariance , correlation , of A and B
mean_a <- delta_a * sum(a * p_a_D)
mean_b <- delta_b * sum(b * p_b_D)
sd_a <- sqrt( delta_a * sum((a-mean_a)^2 * p_a_D) )
sd_b <- sqrt( delta_b * sum((b-mean_b)^2 * p_b_D) )

# Covariance nurmalization is performed with ’brute force ’
# The normalization constant is Z = delta_a*delta_b*sum(exp(z)).
# This is independent of (a,b) so can be calculated outside of the loops.
cov_ab <- 0
for(j in 1:length(a)) {
    for(k in 1:length(b)) {
        cov_ab <- cov_ab + (a[j]-mean_a)*(b[k]-mean_b)*exp(z[j,k])
    }
}

cov_ab <- cov_ab / sum(exp(z))
rho_ab <- cov_ab / (sd_a * sd_b)
cat("  a = ", mean_a, "+/-", sd_a, "\n")
cat("  b = ", mean_b, "+/-", sd_b, "\n")
cat("rho = ", rho_ab, "\n")

In [ ]:
#Professor code



library(tidyverse)
# - Sampling grid for computing posterior
alim <- c(0.0, 4.0)
blim <- c(0.5, 1.5)
Nsamp <- 100
uniGrid <- seq(from=1/(2*Nsamp), to=1-1/(2*Nsamp), by=1/Nsamp)
delta_a <- diff(alim)/Nsamp
delta_b <- diff(blim)/Nsamp
a <- alim[1] + diff(alim)*uniGrid
b <- blim[1] + diff(blim)*uniGrid



# - Generative model
signal <- function(x, a, b, x0, w, t) {
t * (a*exp(-(x-x0)^2/(2*w^2)) + b)
}



# Log posterior
log.post <- function(d, x, a, b, x0, w, t) {
    if(a<0 || b <0) {return(-Inf)}  # the effect of the prior
    sum(dpois(d, lambda=signal(x, a, b, x0, w, t), log=TRUE))
}



# Define model parameters
x0 <- 0 # Signal peak
W<-list(0.1, 0.25, 1, 2, 3) # Signal width
A.true <- 2 # Signal amplitude
B.true <- 1 # Background amplitude
Delta.t <- 5 # Exposure time


mode<-function(w){
    # - Generate the observed data
    set.seed(205)
    xdat <- seq(from=-7*w, to=7*w, by=0.5*w)
    s.true <- signal(xdat , A.true , B.true , x0, w, Delta.t)

    ddat <- rpois(length(s.true), s.true)
    xplot <- seq(from=min(xdat), to=max(xdat), by=0.05*w)
    splot <- signal(xplot , A.true , B.true , x0, w, Delta.t)

    plot(xplot , splot , xlab="x", ylab="Signal+Background counts")
    par(new=TRUE)
    xdat.off <- xdat-0.25
    plot(xdat.off, ddat , type="s", col="firebrick3", lwd=2, xlim=range(xplot), ylim=range(c(splot , ddat)))



    # Compute log unnormalized posterior , z = ln Pˆ*(a,b|D), on a regular grid
    z <- matrix(data=NA, nrow=length(a), ncol=length(b))
    for(j in 1:length(a)) {
        for(k in 1:length(b)) {
            z[j,k] <- log.post(ddat , xdat , a[j], b[k], x0, w, Delta.t)
        }
    }
    z <- z - max(z) # set maximum to zero

    # Plot unnormalized 2D posterior as contours.
    contour(a, b, exp(z), nlevels = 5, labcex = 0.5, lwd = 2, xlab="amplitude , A", ylab="background , B") 
    abline(v=2,h=1,col="grey")



    # Compute normalized marginalized posteriors , P(a|D) and P(b|D)
    # by summing over other parameter. Normalize by gridding.
    p_a_D <- apply(exp(z), 1, sum)
    p_a_D <- p_a_D/(delta_a*sum(p_a_D))
    p_b_D <- apply(exp(z), 2, sum)
    p_b_D <- p_b_D/(delta_b*sum(p_b_D))

    # Compute normalized conditional posteriors , P(a|b,D) and P(b|a,D)
    # using true values of conditioned parameters. Vectorize(func , par)
    # makes a vectorized function out of func in the parameter par.
    p_a_bD <- exp(Vectorize(log.post , "a")(ddat , xdat , a, B.true , x0, w, Delta.t))
    p_a_bD <- p_a_bD/(delta_a*sum(p_a_bD))
    p_b_aD <- exp(Vectorize(log.post , "b")(ddat , xdat , A.true , b, x0, w, Delta.t))
    p_b_aD <- p_b_aD/(delta_b*sum(p_b_aD))



    par(mfrow=c(2,2), mgp=c(2,0.8,0), mar=c(3.5,3.5,1,1), oma=0.1*c(1,1,1,1))

    # Plot the 1D marginalized posteriors
    plot(b, p_b_D, xlab="background , B", yaxs="i",
    ylim=1.05*c(0,max(p_b_D, p_b_aD)), ylab="P(B | D)  and  P(B | A,D)",
    type="l", lwd=2)
    lines(b, p_b_aD, lwd=2, lty=2)
    abline(v=B.true , col="grey")
    plot(a, p_a_D, xlab="amplitude , A", yaxs="i",
    ylim=1.05*c(0,max(p_a_D, p_a_bD)), ylab="P(A | D)  and  P(A | B,D)",
    type="l", lwd=2)
    lines(a, p_a_bD, lwd=2, lty=2)
    abline(v=A.true , col="grey")



    # Compute mean , standard deviation , covariance , correlation , of A and B
    mean_a <- delta_a * sum(a * p_a_D)
    mean_b <- delta_b * sum(b * p_b_D)
    sd_a <- sqrt( delta_a * sum((a-mean_a)^2 * p_a_D) )
    sd_b <- sqrt( delta_b * sum((b-mean_b)^2 * p_b_D) )

    # Covariance nurmalization is performed with ’brute force ’
    # The normalization constant is Z = delta_a*delta_b*sum(exp(z)).
    # This is independent of (a,b) so can be calculated outside of the loops.
    cov_ab <- 0
    for(j in 1:length(a)) {
        for(k in 1:length(b)) {
            cov_ab <- cov_ab + (a[j]-mean_a)*(b[k]-mean_b)*exp(z[j,k])
        }
    }

    cov_ab <- cov_ab / sum(exp(z))
    rho_ab <- cov_ab / (sd_a * sd_b)
    cat("  a = ", mean_a, "+/-", sd_a, "\n")
    cat("  b = ", mean_b, "+/-", sd_b, "\n")
    cat("rho = ", rho_ab, "\n")
}

map(W, mode)